import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";
import GoogleAnalytics from "@/components/googleAnalytics/GoogleAnalytics";
import Footer from "@/components/Footer";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "buckets Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <GoogleAnalytics />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body className={notoSansJP.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
