import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";
import GoogleAnalytics from "@/components/googleAnalytics/GoogleAnalytics";
import Footer from "@/components/Footer";
import RecoilRootRapper from "@/components/RecoilRouteRapper";
import Header from "@/components/Header";

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "buckets Flow",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <GoogleAnalytics />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body className={notoSansJP.className}>
        <RecoilRootRapper>
          <Header />
          <div>{children}</div>
          <Footer />
        </RecoilRootRapper>
      </body>
    </html>
  );
}
